### ISSUE TITLE
Latest.log spam with 1.2.4

### ISSUE THREAD

**Issue by katubug** [CreativeMD/Spice-of-Life-Onion#18]
Hopefully not a misleading title. I loaded into my game after updating a heck-ton of mods, and was experiencing extreme lag. I checked my F3 memory usage, and it was stuck at 99% for as long as I had the screen open. I ended up using Task Manager to exit the game.

My latest.log was filled with the following:
```
[12:44:02] [Server thread/ERROR]: Exception caught during firing event: Cannot invoke "java.util.List.contains(Object)" because "this.appliedEffects" is null
	Index: 4
	Listeners:
		0: NORMAL
		1: ASM: class dev.xkmc.l2library.init.events.EffectSyncEvents onPotionRemoveEvent(Lnet/minecraftforge/event/entity/living/MobEffectEvent$Remove;)V
		2: net.minecraftforge.eventbus.EventBus$$Lambda$1894/0x00000008009dab08@2d8380c8
		3: ASM: class teamrazor.deepaether.event.DAGeneralEvents onEffectRemoved(Lnet/minecraftforge/event/entity/living/MobEffectEvent$Remove;)V
		4: ASM: team.creative.solonion.common.event.SOLOnionEvent@584bf232 onEffectRemove(Lnet/minecraftforge/event/entity/living/MobEffectEvent$Remove;)V
java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "this.appliedEffects" is null
	at TRANSFORMER/solonion@1.2.4/team.creative.solonion.common.benefit.BenefitCapabilityImpl.onEffectRemove(BenefitCapabilityImpl.java:49)
	at TRANSFORMER/solonion@1.2.4/team.creative.solonion.common.event.SOLOnionEvent.onEffectRemove(SOLOnionEvent.java:166)
	at TRANSFORMER/solonion@1.2.4/team.creative.solonion.common.event.__SOLOnionEvent_onEffectRemove_Remove.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_21195_(LivingEntity.java:979)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.commands.EffectCommands.m_246113_(EffectCommands.java:164)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.commands.EffectCommands.m_244829_(EffectCommands.java:50)
	at MC-BOOTSTRAP/brigadier@1.1.8/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.CommandFunction$CommandEntry.m_164875_(CommandFunction.java:96)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.CommandFunction$CommandEntry.m_142134_(CommandFunction.java:90)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ServerFunctionManager$QueuedCommand.m_179985_(ServerFunctionManager.java:135)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ServerFunctionManager$ExecutionContext.m_179977_(ServerFunctionManager.java:210)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ServerFunctionManager.m_179960_(ServerFunctionManager.java:85)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ServerFunctionManager.m_136112_(ServerFunctionManager.java:69)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ServerFunctionManager.m_136115_(ServerFunctionManager.java:63)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ServerFunctionManager.m_136128_(ServerFunctionManager.java:57)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:875)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

And here's the full latest.log: https://gist.github.com/katubug/09f192934d0005704a536ba61e32f026

I'm assuming there's some kind of incompatibility between them, but I'm not sure.

Minecraft: 1.20.1
Forge: 47.2.20
SoL Onion: 1.2.4
Deep Aether: 1.0.3

**Comment by katubug** [comment]
Nope, just tried this without Deep Aether and I'm still having issues. Here's the updated latest.log: https://gist.github.com/katubug/8111570d1f1a5ef1450c6b61d32c7d92

**Comment by katubug** [comment]
Doing some more testing. I switched back to 1.2.3 and the latest.log spam is gone, but my RAM usage is still 95%+ constantly. Spark report shows absolutely nothing going on, and the game is running fine. I'm not sure the memory usage is related to SoL at all at this point.

**Comment by CreativeMD** [comment]
This issue is fixed in the newest version. Thanks for taking the time to report this. Sorry for the trouble.
